(ns fogus.sets
  "Utilities dealing with sets.")

(defn minimize-sets
  "Takes a seq of sets and returns a seq of the mutually different sets. That is, the returned seq
   will contain sets that have no similar items between them."
  [sets]
  (let [commons (apply clojure.set/intersection sets)]
    (reduce (fn [acc tgt]
              (let [prev (last acc)
                    curr (clojure.set/union prev commons)]
                (conj acc (clojure.set/difference tgt curr))))
            [(clojure.set/difference (first sets) commons)]
            (rest sets))))

(comment

  (def decks
    [
     #{"Baleful Stryx"
       "Dralnu, the Lich Lord"
       "Spellseeker"
       "Weathered Wayfarer"
       "Chromatic Lantern"
       "Skullclamp"
       "Taliman of Dominance"
       "Umezawa's Jitte"
       "Winter Orb"
       "Wishclaw Talisman"
       "Demonic Tutor"
       "Fragmentize"
       "Mind Twist"
       "Sevinne's Reclamation"
       "Toxic Deluge"
       "Vindicate"
       "Necropotence"
       "Humility"
       "Daretti, Ingenious Iconoclast"
       "Teferi, Hero of Dominaria"
       "Disenchant"
       "Enlightened Tutor"
       "Mystical Teachings"
       "Swords to Plowshares"
       "Tithe"
       "Canyon Slough"
       "Cephalid Coliseum"
       "City of Brass"
       "Exotic Orchard"
       "Hallowed Fountain"
       "Plateau"
       "Scrubland"
       "Snow-Covered Island"
       "Snow-Covered Swamp"
       "Spire of Industry"
       "Throne of the High City"
       "Tundra"
       "Underground Sea"
       "Watery Grave"
       "Windswept Heath"
       "Snapcaster Mage"
       "Trinket Mage"
       "Urza, Lord High Artificer"
       "Coalition Relic"
       "Crucible of Worlds"
       "Expedition Map"
       "Gilded Lotus"
       "Grim Monolith"
       "Mana Crypt"
       "Mana Vault"
       "Chrome Mox"
       "Mox Opal"
       "Sensei's Divining Top"
       "Sol Ring"
       "Thran Dynamo"
       "Vedlaken Shackles"
       "Talisman of Progress"
       "Arcane Signet"
       "Fabricate"
       "Merchant Scroll"
       "Ponder"
       "Preordain"
       "Vandalblast"
       "Copy Artifact"
       "Treachery"
       "Dack Fayden"
       "Jace, the Mind Sculptor"
       "Tezzeret the Seeker"
       "Narset, Parter of Veils"
       "Brainstorm"
       "Counterspell"
       "Cryptic Command"
       "Fact or Fiction"
       "Fierce Guardianship"
       "Forbid"
       "Force of Negation"
       "Force of Will"
       "Impulse"
       "Mana Drain"
       "Mana Leak"
       "Muddle the Mixture"
       "Mystical Tutor"
       "Remand"
       "Ancient Tomb"
       "Bloodstained Mire"
       "Command Tower"
       "Fabled Passage"
       "Flooded Strand"
       "Lotus Field"
       "Polluted Delta"
       "Prismatic Vista"
       "Steam Vents"
       "Strip Mine"
       "Temple of the False God"
       "Wasteland"
       "Wooded Foothills"}

     #{"Flametongue Kavu"
       "Phyrexian Metamorph"
       "Solemn Simulacrum"
       "Everflowing Chalice"
       "Izzet Signet"
       "Wayfarer's Bauble"
       "Worn Powerstone"
       "Thought Vessel"
       "Amnesia"
       "Rolling Earthquake"
       "Karn Liberated"
       "Archmage's Charm"
       "Condescend"
       "Cyclonic Rift"
       "Daze"
       "Dismiss"
       "Dissolve"
       "Fire / Ice"
       "Into the Roil"
       "Memory Lapse"
       "Rewind"
       "Spell Pierce"
       "Thirst for Knowledge"
       "Whir of Invention"
       "Blast Zone"
       "Izzet Boilerworks"
       "Mystic Sanctuary "
       "Shivan Reef"
       "Snow-Covered Island"
       "Snow-Covered Mountain"
       "Sulfur Falls"
       "Snapcaster Mage"
       "Trinket Mage"
       "Urza, Lord High Artificer"
       "Coalition Relic"
       "Crucible of Worlds"
       "Expedition Map"
       "Gilded Lotus"
       "Grim Monolith"
       "Mana Crypt"
       "Mana Vault"
       "Chrome Mox"
       "Mox Opal"
       "Sensei's Divining Top"
       "Sol Ring"
       "Thran Dynamo"
       "Vedlaken Shackles"
       "Talisman of Progress"
       "Arcane Signet"
       "Fabricate"
       "Merchant Scroll"
       "Ponder"
       "Preordain"
       "Vandalblast"
       "Copy Artifact"
       "Treachery"
       "Dack Fayden"
       "Jace, the Mind Sculptor"
       "Tezzeret the Seeker"
       "Narset, Parter of Veils"
       "Brainstorm"
       "Counterspell"
       "Cryptic Command"
       "Fact or Fiction"
       "Fierce Guardianship"
       "Forbid"
       "Force of Negation"
       "Force of Will"
       "Impulse"
       "Mana Drain"
       "Mana Leak"
       "Muddle the Mixture"
       "Mystical Tutor"
       "Remand"
       "Ancient Tomb"
       "Bloodstained Mire"
       "Command Tower"
       "Fabled Passage"
       "Flooded Strand"
       "Lotus Field"
       "Polluted Delta"
       "Prismatic Vista"
       "Steam Vents"
       "Strip Mine"
       "Temple of the False God"
       "Wasteland"
       "Wooded Foothills"}

     #{"Dralnu, Lich Lord"
       "Arcane Signet"
       "Chromatic Lantern"
       "Chrome Mox"
       "Coalition Relic"
       "Crucible of Worlds"
       "Expedition Map"
       "Gilded Lotus"
       "Grim Monolith"
       "Mana Crypt"
       "Mana Vault"
       "Mox Opal"
       "Sensei's Divining Top"
       "Skullclamp"
       "Sol Ring"
       "Thran Dynamo"
       "Vedlaken Shackles"
       "Winter Orb"
       "Wishclaw Talisman"
       "Demonic Tutor"
       "Fabricate"
       "Merchant Scroll"
       "Mind Twist"
       "Ponder"
       "Preordain"
       "Vandalblast"
       "Humility"
       "Jace, the Mind Sculptor"
       "Tezzeret the Seeker"
       "Teferi, Hero of Dominaria"
       "Brainstorm"
       "Counterspell"
       "Cryptic Command"
       "Enlightened Tutor"
       "Fact or Fiction"
       "Fierce Guardianship"
       "Forbid"
       "Force of Negation"
       "Force of Will"
       "Impulse"
       "Mana Drain"
       "Mana Leak"
       "Muddle the Mixture"
       "Mystical Teachings"
       "Mystical Tutor"
       "Remand"
       "Swords to Plowshares"
       "Tithe"
       "Ancient Tomb"
       "Bloodstained Mire"
       "City of Brass"
       "Command Tower"
       "Fabled Passage"
       "Flooded Strand"
       "Hallowed Fountain"
       "Lotus Field"
       "Plateau"
       "Polluted Delta"
       "Prismatic Vista"
       "Scrubland"
       "Snow-Covered Island"
       "Steam Vents"
       "Strip Mine"
       "Temple of the False God"
       "Tundra"
       "Underground Sea"
       "Wasteland"
       "Watery Grave"
       "Windswept Heath"
       "Wooded Foothills"
       "Everflowing Chalice"
       "Fellwar Stone"
       "Deep Analysis"
       "Quiet Speculation"
       "Regrowth"
       "Toxic Deluge"
       "Wargate"
       "Land Tax"
       "Sylvan Library"
       "The Abyss"
       "Karn Liberated"
       "Liliana of the Veil"
       "Karn, Scion of Urza"
       "Kaya, Ghost Assassin"
       "Abrupt Decay"
       "Ancient Grudge"
       "Cyclonic Rift"
       "Fire / Ice"
       "Lightning Helix"
       "Ray of Revelation"
       "Lightning Bolt"
       "Arcane Sanctum"
       "Breeding Pool"
       "Snow-Covered Swamp"
       "Savannah"
       "Mystic Monastery"
       "Tropical Island"
       "Snow-Covered Mountain"}])

)
